### ISSUE TITLE
stuck at [EB|#LOG:EXITBS:START]

### ISSUE THREAD

**Issue by zitongzhan** [mach-kernel/Dell7820-macOS#2]
Here's the config of my machine 
32G Ram 4*8G DDR4 2666MHz
Xeon Bronze 3104
rx570 8G

OS: macOS Catalina 10.15.5(19F96)

Do you know how to solve it? Thanks in advance!

**Comment by zitongzhan** [comment]
I solved this issue by adding
```
<key>RebuildAppleMemoryMap</key>
<true/>

<key>SetupVirtualMap</key>
<false/>
```

**Comment by mach-kernel** [comment]
I'm going to make changes to the config to add these settings. Thanks!
